version: '3.9'

services:
  
  db:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=djangoDb
      - POSTGRES_USER=erik1288
      - POSTGRES_PASSWORD=ingeniero010

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - pgadminData:/var/lib/pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=ingeniero010
    depends_on:
      - db

  web:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    restart: always
    container_name: Django
    volumes:
      - .:/code
      - static_volume:/code/static/
      - media_volume:/code/media/
    command: >
      sh -c "gunicorn listProduct.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=djangoDb
      - POSTGRES_USER=erik1288
      - POSTGRES_PASSWORD=ingeniero010
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - 9656:80
    depends_on:
      - web
      
volumes:
  data:
  pgadminData:
  static_volume:
  media_volume: