services:

  db:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: productsDB
      MYSQL_USER: erik1288
      MYSQL_PASSWORD: ingeniero010
      MYSQL_ROOT_PASSWORD: ingeniero010
    volumes:
      - /ApplistadoProductos:/etc/mysql/conf.d
      
  web:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /ApplistadoProductos:/etc/mysql/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - db