# Generated by Django 3.2.17 on 2023-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_typecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=models.FileField(default=' ', null=True, upload_to='uploads/contact'),
        ),
    ]
